//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentBindingSpec) DeepCopyInto(out *AgentBindingSpec) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Approve != nil {
		in, out := &in.Approve, &out.Approve
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentBindingSpec.
func (in *AgentBindingSpec) DeepCopy() *AgentBindingSpec {
	if in == nil {
		return nil
	}
	out := new(AgentBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ISOCacheHistoryEntry) DeepCopyInto(out *ISOCacheHistoryEntry) {
	*out = *in
	in.UploadedAt.DeepCopyInto(&out.UploadedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ISOCacheHistoryEntry.
func (in *ISOCacheHistoryEntry) DeepCopy() *ISOCacheHistoryEntry {
	if in == nil {
		return nil
	}
	out := new(ISOCacheHistoryEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ISOCacheSpec) DeepCopyInto(out *ISOCacheSpec) {
	*out = *in
	out.CheckInterval = in.CheckInterval
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ISOCacheSpec.
func (in *ISOCacheSpec) DeepCopy() *ISOCacheSpec {
	if in == nil {
		return nil
	}
	out := new(ISOCacheSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ISOCacheStatus) DeepCopyInto(out *ISOCacheStatus) {
	*out = *in
	in.CheckedAt.DeepCopyInto(&out.CheckedAt)
	in.UploadedAt.DeepCopyInto(&out.UploadedAt)
	if in.History != nil {
		in, out := &in.History, &out.History
		*out = make([]ISOCacheHistoryEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ISOCacheStatus.
func (in *ISOCacheStatus) DeepCopy() *ISOCacheStatus {
	if in == nil {
		return nil
	}
	out := new(ISOCacheStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalObjectReference) DeepCopyInto(out *LocalObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalObjectReference.
func (in *LocalObjectReference) DeepCopy() *LocalObjectReference {
	if in == nil {
		return nil
	}
	out := new(LocalObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OwnedVMStatus) DeepCopyInto(out *OwnedVMStatus) {
	*out = *in
	if in.AgentRef != nil {
		in, out := &in.AgentRef, &out.AgentRef
		*out = new(v1.ObjectReference)
		**out = **in
	}
	if in.MachineRef != nil {
		in, out := &in.MachineRef, &out.MachineRef
		*out = new(v1.ObjectReference)
		**out = **in
	}
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OwnedVMStatus.
func (in *OwnedVMStatus) DeepCopy() *OwnedVMStatus {
	if in == nil {
		return nil
	}
	out := new(OwnedVMStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlannedActionStatus) DeepCopyInto(out *PlannedActionStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlannedActionStatus.
func (in *PlannedActionStatus) DeepCopy() *PlannedActionStatus {
	if in == nil {
		return nil
	}
	out := new(PlannedActionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingPolicySpec) DeepCopyInto(out *ScalingPolicySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingPolicySpec.
func (in *ScalingPolicySpec) DeepCopy() *ScalingPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ScalingPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMTemplateSpec) DeepCopyInto(out *VMTemplateSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMTemplateSpec.
func (in *VMTemplateSpec) DeepCopy() *VMTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(VMTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VsphereAgentPool) DeepCopyInto(out *VsphereAgentPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VsphereAgentPool.
func (in *VsphereAgentPool) DeepCopy() *VsphereAgentPool {
	if in == nil {
		return nil
	}
	out := new(VsphereAgentPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VsphereAgentPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VsphereAgentPoolList) DeepCopyInto(out *VsphereAgentPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VsphereAgentPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VsphereAgentPoolList.
func (in *VsphereAgentPoolList) DeepCopy() *VsphereAgentPoolList {
	if in == nil {
		return nil
	}
	out := new(VsphereAgentPoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VsphereAgentPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VsphereAgentPoolSpec) DeepCopyInto(out *VsphereAgentPoolSpec) {
	*out = *in
	out.HostedClusterRef = in.HostedClusterRef
	out.NodePoolRef = in.NodePoolRef
	out.InfraEnvRef = in.InfraEnvRef
	in.VSphere.DeepCopyInto(&out.VSphere)
	out.Template = in.Template
	in.Agent.DeepCopyInto(&out.Agent)
	out.Scaling = in.Scaling
	out.ISO = in.ISO
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VsphereAgentPoolSpec.
func (in *VsphereAgentPoolSpec) DeepCopy() *VsphereAgentPoolSpec {
	if in == nil {
		return nil
	}
	out := new(VsphereAgentPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VsphereAgentPoolStatus) DeepCopyInto(out *VsphereAgentPoolStatus) {
	*out = *in
	if in.OwnedVMs != nil {
		in, out := &in.OwnedVMs, &out.OwnedVMs
		*out = make([]OwnedVMStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PlannedActions != nil {
		in, out := &in.PlannedActions, &out.PlannedActions
		*out = make([]PlannedActionStatus, len(*in))
		copy(*out, *in)
	}
	in.ISO.DeepCopyInto(&out.ISO)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VsphereAgentPoolStatus.
func (in *VsphereAgentPoolStatus) DeepCopy() *VsphereAgentPoolStatus {
	if in == nil {
		return nil
	}
	out := new(VsphereAgentPoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VspherePlacementSpec) DeepCopyInto(out *VspherePlacementSpec) {
	*out = *in
	out.CredentialsSecretRef = in.CredentialsSecretRef
	if in.VMTags != nil {
		in, out := &in.VMTags, &out.VMTags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VspherePlacementSpec.
func (in *VspherePlacementSpec) DeepCopy() *VspherePlacementSpec {
	if in == nil {
		return nil
	}
	out := new(VspherePlacementSpec)
	in.DeepCopyInto(out)
	return out
}
